name: CI

# Triggers that start the workflow
on:
  push:

  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Builds Docker image
        run: docker build -t shipit3 .
      - name: Run docker image
        run: docker run --rm shipit3

  